### ISSUE TITLE
元文書の更新個所を反映して修正

### ISSUE THREAD

**Issue by akie-m** [SMizutani/Logic-EES-WEB#11]
下記のファイルの修正です。
_07_Hot_Water_Supply_System/Hot_Water_Demand.ipynb

元PDFの更新部分をipynbに反映しました。数式と添え字説明を追加しています。
ブランチは下記になります。
task/reflect_the_update_of_the_original_doc

ご確認をお願いします。

**Comment by SMizutani** [comment]
ありがとうございます。了解しました。
