### ISSUE TITLE
テキストに関する軽い修正

### ISSUE THREAD

**Issue by akie-m** [SMizutani/Logic-EES-WEB#12]
下記ファイルの修正です。
_07_Hot_Water_Supply_System/Hot_Water_Demand.ipynb

誤字修正など、軽いテキスト周りの修正を含めています。
ブランチは下記になります。
task/some_minor_text_corrections

ご確認をお願いします。

**Comment by SMizutani** [comment]
ありがとうございます。確認しました。

**Comment by SMizutani** [comment]
後からすいません、eletic -> electricに修正しておきます。
