### ISSUE TITLE
07＞Hot_Water_Demand.ipynbの追加修正

### ISSUE THREAD

**Issue by akie-m** [SMizutani/Logic-EES-WEB#14]
Hot_Water_Demand.ipynbのマークダウンのエリア内の追加修正をプッシュしました。
主な修正点は
・テキストの英語化
・表中の数字修正（1か所）
・テキストセルの位置調整
です。

前回までと同様にブランチを切ってしまっていますが、こちらは水谷さんで他のコミット内容とまとめて大本にプルリクしていただく…という流れになるのでしょうか？
もしブランチを切らないほうがよければ、対処を考えますのでご返信などいただければ幸いです。

どうぞよろしくお願いいたします。

※追記です。
記載を忘れてしまっていましたが、こちらの修正は
task/text_editing　ブランチとしてプッシュしています。
よろしくお願いいたします。

**Comment by SMizutani** [comment]
マージしました。
