### ISSUE TITLE
第四章 第六節 電気蓄熱暖房器PDFについて

### ISSUE THREAD

**Issue by akie-m** [SMizutani/Logic-EES-WEB#15]
表題のPDFにつきまして
https://www.kenken.go.jp/becc/documents/house/4-6_160401_v03_PVer02.pdf

一点、不備かと思われる個所がありました。

▼2ページ目　6. 暖房エネルギー消費量＞6.1 消費電力量　の添え字説明
『𝑄𝑇,𝐻,𝑑,𝑡 ：日付𝑑の時刻𝑡における処理暖房負荷（MJ/h）』
とありますが、こちらは、第四章第四節の2ページ目にある
『𝑄𝑇,𝐻,𝑑,𝑡 ：日付𝑑の時刻𝑡における１時間当たりの処理暖房負荷（MJ/h）』
と同じものかと思われます。

＞第四章第四節 FF 暖房機
https://www.kenken.go.jp/becc/documents/house/4-4_160401_v03_PVer02.pdf

ご確認の程、よろしくお願いいたします。

**Comment by SMizutani** [comment]
ありがとうございます。
ご指摘の通り"1時間当たりの"を追加するのが望ましいと思います。
確認します。

**Comment by SMizutani** [comment]
先方に確認してもらっていて仕様書通りに書いてくれているので一旦クローズします。
