### ISSUE TITLE
第四章 第八節 ルームエアコンディショナー付温水床暖房PDFについて

### ISSUE THREAD

**Issue by akie-m** [SMizutani/Logic-EES-WEB#16]
表題のPDFにつきまして
https://www.kenken.go.jp/becc/documents/house/4-8_180402_v05_PVer0201.pdf

不備かもと思われる個所のピックアップです。

▼3ページ目　7.1 熱源機の消費電力量　の計算式(3)
説明文中では”E_{E,hs,d,t}”を求めるための式となっていますが、
計算式では”E_{E,hs,H,d,t}”となっています。

▼5ページ目　7.2 圧縮機の消費電力量　の計算式(10)
説明文中では”q_{loss,H,hs,d,t}”を求めるための式となっていますが、
計算式では”q_{loss,H,hs,H,d,t}”となっています。

▼6ページ目　7.4 熱源機の暖房出力と未処理暖房負荷　の計算式(15)
計算式中の”C_{def,H,d,t}”ですが、”C_{df,H,d,t}”の記述ミスかと思われます。

ご確認の程、よろしくお願いいたします。

**Comment by SMizutani** [comment]
ありがとうございます。
”E_{E,hs,d,t}”
”q_{loss,H,hs,d,t}”
”C_{df,H,d,t}”
が正と思いますが確認します。

**Comment by SMizutani** [comment]
先方に確認してもらっていて仕様書通りに書いてくれているので一旦クローズします。
